name: "Require labels"

on:
  pull_request:
   types: [opened, labeled, unlabeled, synchronize]

jobs:
  verify_label:
    runs-on: ubuntu-latest
    name: Require labels
    steps:
    - name: Verify Pull Request Labels
      uses: jesusvasquez333/verify-pr-label-action@v1.1.0
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        valid-labels: 'bug, fix, enhancement, feature, chore'
